apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # same name with memcached hostname in application.properties file
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
    - port: 11211
      targetPort: vprocache01-port
      protocol: TCP
