apiVersion: v1
kind: Service
metadata:
  name: vpromq01 # same name with memcached hostname in application.properties file
spec:
  type: ClusterIP
  selector:
    app: vpromq01
  ports:
    - port: 15672
      targetPort: vpromq01-port
      protocol: TCP
