apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: thanachartdevs/vprofileapp
          ports:
            - name: vproapp-port
              containerPort: 8080
      # Need DB created before application
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vprodb; do echo waiting for mydb; sleep 2; done;"
            ]
      # Need Memcached created before application
      initContainers:
        - name: init-memcache
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup vpromc; do echo waiting for mydb; sleep 2; done;"
            ]
